<?php
/**
 * Created by PhpStorm.
 * User: jenny
 * Date: 6/7/2018
 * Time: 12:51 PM
 */

class CookiePolicyPage extends Page
{
    public function requireDefaultRecords()
    {
        parent::requireDefaultRecords();
        if(!CookiePolicyPage::get()->first()){
            $cookiePage = CookiePolicyPage::create();
            $cookiePage->Title = 'GDPR Cookie Policy';
            $cookiePage->write();
            $cookiePage->doPublish();
        }
    }

    private static $db = array(

    );


    public function getCMSFields()
    {
        $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub

        return $fields;
    }
}

