<?php
/**
 * Created by PhpStorm.
 * User: jenny
 * Date: 6/7/2018
 * Time: 12:51 PM
 */

class PolicyPage extends Page
{
    public function requireDefaultRecords()
    {
        parent::requireDefaultRecords();
        if(!PolicyPage::get()->first()){
            $privacyPage = PolicyPage::create();
            $privacyPage->Title = 'Privacy Policy';
            $privacyPage->write();
            $privacyPage->doPublish();
        }
    }

    private static $db = array(

    );


    public function getCMSFields()
    {
        $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub

        return $fields;
    }
}

