<?php
/**
 * Created by PhpStorm.
 * User: jenny
 * Date: 6/7/2018
 * Time: 12:51 PM
 */

class TermsPage extends Page
{
    public function requireDefaultRecords()
    {
        parent::requireDefaultRecords();
        if(!TermsPage::get()->first()){
            $termsPage = TermsPage::create();
            $termsPage->Title = 'GDPR Terms of Use';
            $termsPage->write();
            $termsPage->doPublish();
        }
    }

    private static $db = array(

    );


    public function getCMSFields()
    {
        $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub

        return $fields;
    }
}

