---
Name: masterrecordroutes
After:
  - '#rootroutes'
  - '#modelascontrollerroutes'
  - '#restfulserverroutes'
---
Director:
  rules:
    '$Action/access//$Action/$ID': 'MasterRecordPage_Controller',
